local HOME = os.getenv('HOME')

local dir = HOME .. '/.config/awesome/theme/icons/'

return {
    --tags
    chrome = dir .. '/firefox.svg',
    code = dir .. '/code.svg',
    social = dir .. '/forum.svg',
    folder = dir .. '/folder.svg',
    music = dir .. '/music.svg',
    game = dir .. '/google-controller.svg',
    lab = dir .. '/flask.svg',
    terminal = dir .. '/terminal.svg',
    art = dir .. '/art.svg',
    --others
    menu = dir .. '/menu.svg',
    logo = dir .. '/logo.svg',
    settings = dir .. '/settings.svg',
    close = dir .. '/close.svg',
    logout = dir .. '/logout.svg',
    sleep = dir .. '/power-sleep.svg',
    power = dir .. '/power.svg',
    lock = dir .. '/lock.svg',
    restart = dir .. '/restart.svg',
    search = dir .. '/magnify.svg',
    monitor = dir .. '/laptop.svg',
    wifi = dir .. '/wifi.svg',
    wifi_off = dir .. '/wifi_off.svg',
    volume = dir .. '/volume-high.svg',
    microphone = dir .. '/microphone.svg',
    muted = dir .. '/volume-mute.svg',
    brightness = dir .. '/brightness-7.svg',
    chart = dir .. '/chart-areaspline.svg',
    memory = dir .. '/memory.svg',
    harddisk = dir .. '/harddisk.svg',
    thermometer = dir .. '/thermometer.svg',
    plus = dir .. '/plus.svg',
    minus = dir .. '/minus.svg',
    network = dir .. '/network.svg',
    upload = dir .. '/upload.svg',
    download = dir .. '/download.svg',
    warning = dir .. '/warning.svg',
    lan = dir .. '/lan.svg',
    lan_off = dir .. '/lan_off.svg',
    calendar = dir .. '/calendar.svg',
    brush = dir .. '/brush.svg',
    bluetooth = dir .. '/bluetooth.svg',
    bluetooth_off = dir .. '/bluetooth-off.svg',
    bios = dir .. '/bios.svg',
    package = HOME .. '.config/awesome/widget/package-updater/icons/package.svg',
    about = dir .. '/info.svg',
    mouse = dir .. '/mouse.svg',
    user = dir .. '/user.svg',
    qr_code = dir .. '/qr_code.svg',
    --png's
    unknown = dir .. '/noicon.svg'
}
